// Code generated by "stringer -type=IncidentType"; DO NOT EDIT.

package incident

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNKNOWN_IT-0]
	_ = x[TEST_IT-1]
	_ = x[ACTIVE_IT-2]
}

const _IncidentType_name = "UNKNOWN_ITTEST_ITACTIVE_IT"

var _IncidentType_index = [...]uint8{0, 10, 17, 26}

func (i IncidentType) String() string {
	if i < 0 || i >= IncidentType(len(_IncidentType_index)-1) {
		return "IncidentType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IncidentType_name[_IncidentType_index[i]:_IncidentType_index[i+1]]
}
