// Code generated by "stringer -type=IncidentStatus"; DO NOT EDIT.

package incident

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNKNOWN_IS-0]
	_ = x[ACTIVE_IS-1]
	_ = x[RESOLVED_IS-2]
	_ = x[ARCHIVED_IS-3]
}

const _IncidentStatus_name = "UNKNOWN_ISACTIVE_ISRESOLVED_ISARCHIVED_IS"

var _IncidentStatus_index = [...]uint8{0, 10, 19, 30, 41}

func (i IncidentStatus) String() string {
	if i < 0 || i >= IncidentStatus(len(_IncidentStatus_index)-1) {
		return "IncidentStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IncidentStatus_name[_IncidentStatus_index[i]:_IncidentStatus_index[i+1]]
}
