// Code generated by ogen, DO NOT EDIT.

package rootly

import (
	"context"
	"net/http"

	"github.com/go-faster/errors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleBearerAuth handles bearer_auth security.
	HandleBearerAuth(ctx context.Context, operationID string, t BearerAuth) (context.Context, error)
}

func (s *Server) securityBearerAuth(ctx context.Context, operationID string, req *http.Request) (context.Context, error) {
	var t BearerAuth
	t.Token = req.Header.Get("Authorization")
	return s.sec.HandleBearerAuth(ctx, operationID, t)
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// BearerAuth provides bearer_auth security value.
	BearerAuth(ctx context.Context, operationID string) (BearerAuth, error)
}

func (s *Client) securityBearerAuth(ctx context.Context, operationID string, req *http.Request) error {
	t, err := s.sec.BearerAuth(ctx, operationID)
	if err != nil {
		return errors.Wrap(err, "security source \"BearerAuth\"")
	}
	req.Header.Set("Authorization", t.Token)
	return nil
}
